<div class="front-searchcourse dialog" style="position: relative; height: 134px; top: 108px; width: 560px ! important; font-size: 22px;"> 
    <p style="margin-top: 0px; position: relative; text-align: center; top: 29px;">
        Welcome, Heechiker!
    </p>
    <p style="position: relative; text-align: center; top: 19px;">
        Are you looking to share a ride?
    </p>
</div>

<div style="width: 600px; margin: 0px auto; position: relative; top: 183px;">
    <a href="/facebook/details/?type=join" style="float:left;">
        <img src="/img/button_join_up.png" />
    </a>
    <a href="/facebook/details/?type=driver" style="float:right;">
        <img src="/img/button_driver_up.png" />
    </a>
</div>