<div class="front-searchcourse dialog" style="position: relative;top: 69px; height: 200px;"> 
    <div>
        <table style="margin: 0px auto; width: 588px;">
            <tbody><tr>
                <td style="padding: 5px; vertical-align: middle; width: 161px;" rowspan="2">
                    <img height="100" width="138" src="/img/Error.png">
                </td>
                <td style="height: 55px; vertical-align: middle;">
                    <h1 style="color: #E62A59;">
                        Login required
                    </h1>
                    <p>
                        You have to be logged in to facebook and authrize this app to proceed
                    </p>
                    <a href="<?php echo $this -> sLoginUrl; ?>" class="fbc-login-register-button">
                        Login
                    </a>
                </td>
            </tr>
        </tbody></table>
    </div>
</div>