<?php
/**
 * the base layout - general html elements that are identical in all pages
 * all the pages layout will extend this
 */
?> 

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://ogp.me/ns/fb#">  
    <head> 
        <?php  
            $this->headTitle()->prepend('Heechikerz');
            echo $this->headTitle(); 
        ?> 
        <?php 
            echo $this->headMeta(); 
        ?> 
        <!--<meta property="og:image" content="http://www.nerdeez.com/img/90X90.png"/> -->
        <?php 
            /*$this->headLink(array('rel' => 'SHORTCUT ICON',
                                  'href' => '/img/favicon.ico'), 
                                  'PREPEND');
            echo $this->headLink(); */
        ?> 
        <?php  
            
            echo $this->headStyle(); 
        ?> 
        <link rel="stylesheet/less" type="text/css" href="/styles/styles.less" />
        <?php 
            //attach common javascriopt files
            echo $this->headScript(); 
            
        ?> 
        
        <?php
        $cache_expire = 60*60*24*365;
        header("Pragma: public");
        header("Cache-Control: max-age=".$cache_expire);
        header('Expires: ' . gmdate('D, d M Y H:i:s', time()+$cache_expire) . ' GMT');
        ?>
        <script src="//connect.facebook.net/en_US/all.js"></script>
      
         <!--<script src="//connect.facebook.net/en_US/all.js"></script>-->
        <!--<script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-36919461-1']);
            _gaq.push(['_trackPageview']);

            (function() {
              var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
              ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
              var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        </script>-->
    </head> 
    <body>
        <div id="fb-root"></div>
        <script>
          window.fbAsyncInit = function() {
            // init the FB JS SDK
            FB.init({
              appId      : '<?php echo $this -> layout() -> sFBID; ?>', // App ID from the App Dashboard
              channelUrl : '//www.<?php echo $this->layout() -> sUrl; ?>/channel.html', // Channel File for x-domain communication
              status     : true, // check the login status upon init?
              cookie     : true, // set sessions cookies to allow your server to access the session?
              xfbml      : true  // parse XFBML tags on this page?
            });

            // Additional initialization code such as adding Event Listeners goes here

          };

          // Load the SDK's source Asynchronously
          // Note that the debug version is being actively developed and might 
          // contain some type checks that are overly strict. 
          // Please report such bugs using the bugs tool.
          (function(d, debug){
             var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
             if (d.getElementById(id)) {return;}
             js = d.createElement('script'); js.id = id; js.async = true;
             js.src = "//connect.facebook.net/en_US/all" + (debug ? "/debug" : "") + ".js";
             ref.parentNode.insertBefore(js, ref);
           }(document, /*debug*/ false));
        </script>
        
        
        <?php /* NESTED LAYOUT SUPPORT */ ?> 
        <?php 
            if($this->layout()->nestedLayout){
                $this->layout()->setLayout($this->layout()->nestedLayout);
            } 
            else{
                $this->layout()->setLayout('default');
            }
            //echo $this->layout()->render();

        ?> 
        
        
         
        
        
        <!-- begin loading screen -->
        <div class="glass" style="z-index: 100;" id="loadingball">
            <div class="loading" 
                 style="left: 50%;position: relative;top: 50%;">
            </div>
        </div>
        <!-- end loading screen  -->
        
        
        
        
        <!-- Begin page -->
        <div id="canvas">
            
            <!-- Begin header -->
            <div id="header">
                <div style="margin: 0 auto; height: 100%; width: 245px;">
                    <a href="/" >
                        <img src="/img/logo_heetchikerz.png" />
                    </a>
                </div>
            </div>
            <!-- End header --> 
            
            <!-- begin Body -->
            <div id="body">
                <?php echo $this->layout()->render(); ?>
            </div>
            <!-- end Body -->
            
            <!-- begin footer -->
            <div id="footer">
                
            </div>
            <!-- end footer -->
            
        </div>
        <!-- End page -->
        
        <!-- common js initialization here -->
        <script type="text/javascript">
            initCommonActions();
        </script>
        <!-- end common -->
        
    </body> 
</html>
